### PR TITLE
Fix to show help text

### LINKED ISSUE #136: Help text is not showing when used in actions
Not sure if this package is meant to be used in actions but so far everything seems to work great, except for the help text that is missing.

### PR DESCRIPTION
**Pull request by vkazakevich**
Hi 👋

I made a fix so that help text will be displayed in the dependent fields. 

Fixes  #136

### CODE REVIEW

**Review by shibby — APPROVED** [review]

**Comment by aedart** [comment]
When can this be merged & released? It would be really nice to have help texts work for input fields.

**Comment by duckzland** [comment]
Tested and working

**Comment by aedart** [comment]
@duckzland Thank you. Might I ask when you plan a next release?

**Comment by duckzland** [comment]
> 
> 
> @duckzland Thank you. Might I ask when you plan a next release?

Sorry I'm not the maintainer for this repo.

**Comment by ragingdave** [comment]
Thanks for the addition!

**Pull request merged**
