### PR TITLE
Stop on no fields

### PR DESCRIPTION
**Pull request by bsormagec**
When i am creating dynamic fields with NovaRequest::createFrom() its returning error. This will fix it.

### CODE REVIEW

**Comment by bsormagec** [comment]
I am using it on action  @wize-wiz and its returning error 

`message: "Invalid argument supplied for foreach()", exception: "ErrorException",…}
exception: "ErrorException"
file: "/Users/****/****/****/vendor/epartment/nova-dependency-container/src/HasDependencies.php"
line: 96
message: "Invalid argument supplied for foreach()"`

**Comment by imgoingtoyellalldaylong** [comment]
Could you show me the how you implemented it? Just small outtakes will do.

**Comment by wize-wiz** [comment]
@bsormagec could you show me how you implemented it? Just small outtakes will do.

**Comment by bsormagec** [comment]
```php

$actionRequest = ActionRequest::createFrom(\request());

$purchase = $actionRequest->findResourceOrFail();
$receivableItems = $purchase->receivableItems()->get();

foreach ($receivableItems as $receivableItem) {
            
                /** @var \Illuminate\Database\Eloquent\Model $modelData */
                $modelData = $receivableItem->model()->first();
                //dump($modelData);
                $fieldArray[] = Heading::make("$modelData->name - Total: $receivableItem->total_quantity / Received: $receivableItem->received_quantity ID : $receivableItem->id");
                $fieldArray[] = Boolean::make(__('Dosya Yükle'), "import[$receivableItem->id][upload_file]");
                $fieldArray[] = NovaDependencyContainer::make([
                    File::make(__('Excel Dosyası'), "import[$receivableItem->id][excel_file]")
                ])->dependsOn("import[$receivableItem->id][upload_file]", true);
                $fieldArray[] = NovaDependencyContainer::make([
                    Textarea::make(__('Seri Numaralarını Yazınız'), "import[$receivableItem->id][serials]")
                        ->help('Her satırda bir seri numarası olacak biçimde yapıştırınız')
                ])->dependsOn("import[$receivableItem->id][upload_file]", false);
                $fieldArray[] = Text::make(__('Birim Fiyat'), "import[$receivableItem->id][unit_cost]");
                $fieldArray[] = HiddenField::make("import[$receivableItem->id][item_type]")->default(class_basename($modelData));
            }
```

I am building dynamic form fields by some property of resources. You can see sample code above.

**Pull request closed without merging**
