### PR TITLE
Add dependsOnNot

### LINKED ISSUE #94: Add Ability for dependsOnNot
This would be very helpful to be able to display either fallback detail page information/heading in case of an empty panel due to all other fields being hidden by a dependsOn clause.

### PR DESCRIPTION
**Pull request by ragingdave**
Fixes #94

### CODE REVIEW

**Comment by wize-wiz** [comment]
@ragingdave Looks solid! I'll give it a test drive tonight and merge it if I have nothing else to add.

**Comment by wize-wiz** [comment]
@ragingdave Dunn Tire? So you literally can drive your bike to the Niagara Falls?

**Comment by ragingdave** [comment]
Lol That I can and have done (of course by bike I mean motorcycle)

**Comment by ragingdave** [comment]
Any chance you've had a look?

**Comment by wize-wiz** [comment]
@ragingdave He Dave, I'm sorry, currently I'm on tight deadlines and somehow those deadlines won't go away!...

I'll try to look into it end of the week. Are you a freelancer btw?

And didn't David Cox Jr. die in 1885? 😁

**Comment by ragingdave** [comment]
No worries got deadlines of my own too :)... I don't think I died in 1885 but who knows lol. Not a dedicated freelancer at the moment but if a cool project comes along who knows right? We all turn into freelancers then

**Comment by wize-wiz** [comment]
@ragingdave turn into a freelancer you mean like mutating? I don't know how you guys turn into freelancers on the other side of the ocean, but if it's by mutating .. oh boy! I wish I get 6 pairs of arms!

**Comment by lopandpe** [comment]
Hi there! Just to know, @wize-wiz could you review this? Just to know. If this is going to be pulled soon, I'll wait for it <3

**Comment by ragingdave** [comment]
@wize-wiz I certainly don't want to come off as naggy....but any chance this might make it soon?

**Comment by desaintflorent** [comment]
I would be really intrested for this too.
Do you have any idea of timing ?

**Comment by ragingdave** [comment]
@wize-wiz I get that we are all busy but this isn't a huge package change, and seems like other people want/need this too. I've now gotten to the point of just using my fork in my project due to how long it's taking to get in here. I understand it's open source and you do what you can....but I mean 4-5 months....there has to be some kind of time in there for this kind of thing.

**Comment by Aylarius** [comment]
@ragingdave @wize-wiz  **dependsOnNot** is unfortunately still not available as no new release has been created. Could you please release it? That would be super helpful!

**Comment by ragingdave** [comment]
New release should be good to go

**Pull request merged**
