### PR TITLE
fix validation for NovaDependencyContainer child fields

### PR DESCRIPTION
**Pull request by tufankilicaslan**
This PR for fixing the validation problem for NovaDependencyContainer child fields.

edit: Also, with the last commit,  I managed to apply validation for Action fields.

### CODE REVIEW

**Comment by webhealer** [comment]
It would better if we can improve this code to apply rules automatically by getting depended field, so not to have write depended field inside the rule again.

**Comment by webhealer** [comment]
Also need to find a way to apply rules for Action fields. Action fields using different method to generate fields. I will check how we can overwrite it.

**Comment by BobbyBorisov** [comment]
@webhealer I forked your repo but 
 NovaDependencyContainer::make([
                Text::make(__('assets.price_per_time'), 'price_per_minute')->rules(['required']),
 ])->dependsOn('mode', 'time'),

doesn't not seem to work? Any clues?

**Comment by TheoKouzelis** [comment]
@webhealer PR has fixed a conflict which appeared in later versions on Nova. I have now been able to update to Nova v1.3.1 and this package still works thanks to @webhealer PR. I think it should be merged

**Comment by webhealer** [comment]
@TheoKouzelis  thanks for reviewing my codes. Just pushed another commit for applying validation for Action fields.

**Comment by tiagoraposeiraff** [comment]
@tufankilicaslan any idea when your PR might be reviewed and merged in by the repo owners? Looking forward to use this in Actions!

**Comment by tufankilicaslan** [comment]
@tiagoraposeiraff  really I don't know :confused:  I hope it will be reviewed and merged soon.

For a temporary solution you can use my or your own forked branch  like this way:

modify "require" section,   add  "dev-master"  for version.
```
    "require": {
            ....,
           "epartment/nova-dependency-container": "dev-master",
           ....
   }
```

for repositories add following "vcs".

```
    "repositories": [

        {
            "type": "vcs",
            "url": "https://github.com/tufankilicaslan/nova-dependency-container"
        },
 ]
```
after "composer update", you can use this PR.

**Comment by phuclh** [comment]
I already use the trait in the resource, but the validation still doesn't work :(. Any solution for that? Thanks. I am using Nova 2.0

**Comment by tufankilicaslan** [comment]
@phuclh  are you using master branch or my forked branch?

**Comment by BobbyBorisov** [comment]
@tufankilicaslan i am using the forked branch on nova 2.0 and it does not work? any idea why

**Comment by Gummby** [comment]
@tufankilicaslan same issue as @BobbyBorisov. The rules maybe broken in Nova 2.0.9

`                        
NovaDependencyContainer::make([
   DateTime::make('Active from', 'start_date')
   ->rules(['required']),
])->dependsOnNotEmpty('date')
`

**Comment by nickfla1** [comment]
@tufankilicaslan Just installed using your forked branch but I'm still having the same issue

**Pull request merged**
