### PR TITLE
add NestedForm integration

### PR DESCRIPTION
**Pull request by smskin**
Resolved conflicts of PR https://github.com/epartment/nova-dependency-container/pull/146
----------
Nova Nested Form is a useful package to create related resource inline using a cool UX.
This package has some problem if it contains a DependencyContainer field.

This PR allow these 2 packages to cooperate.

NestedForm uses a custom field syntax for nested purpose (based on PHP square bracket array syntax).
This PR change standard behavior of DependencyContainer to use this syntax if it used inside of a NestedForm.
It is obviously completely retro-compatible.

It fixes these PRs
yassilah/laravel-nova-nested-form#26
yassilah/laravel-nova-nested-form#114

### CODE REVIEW

**Comment by pitylee** [comment]
It seems that this won't be merged soon, can you put your package to packagist @smskin ?

**Comment by smskin** [comment]
Due to the long response, I had to recreate the PR to release the master branch. the master branch will be used to create a package in the packagist.
New PR: https://github.com/epartment/nova-dependency-container/pull/202
New package with fixes: https://packagist.org/packages/smskin/nova-dependency-container

@dchiorean @NoahNxT @TheSETJ @pitylee like pls the new request

**Comment by NoahNxT** [comment]
@smskin nice! But don't forget to update the documentation, because the composer require is not from epartment on your package.

Maybe instead of creating a new package, did you consider sending him a mail to be a contributor? So many projects already use this version of nested form, it would be better that this package keeps maintained 😃

**Comment by smskin** [comment]
@NoahNxT Unfortunately, the author of the package does not respond to my messages. You are right, this package is used by a large number of developers. I would really like the authors to maintain their library.

**Comment by wize-wiz** [comment]
@smskin I'm currently not in any projects, sort of a timeout from developing anything IT related. 

Tell me what you need, I can give you access to maintain this package if you like, or anybody else who might be interested.

This package, I believe, is still used for a bigger project I created. I'll have to ask if they still use this package (a specific modified branch), that's the only thing that needs to be left untouched.

**Comment by NoahNxT** [comment]
@smskin open-source has a lot of advantages but sadly in this case it can also be a disadvantage. Releasing this package under another name/organization isn't really ethical under open-source.

I've really been thinking to take over an re-release it under my own name/organization but idk what to do... This is a package with a lit of potential and which solves a real pain of Nova. It would be sad if this would get lost between other unmaintained packages.

**Comment by wize-wiz** [comment]
@NoahNxT Then tell me what you need. If you know how to maintain packages everyone is free to join.

**Comment by wize-wiz** [comment]
@smskin @NoahNxT I got admin rights from the original author years ago to maintain this package because I was too in the same situation as you are now. This time I'm the guy who doesn't respond to anything :D.

**Comment by smskin** [comment]
> Releasing this package under another name/organization isn't really ethical under open-source.

@NoahNxT I completely agree with you. But unfortunately I couldn't wait for the bug fix any further

**Comment by NoahNxT** [comment]
@wize-wiz i'd like to be a maintainer as well, we use Nova a lot here and especially this package. We can easily support you and the team to get this package well maintained.

**Comment by smskin** [comment]
> Tell me what you need, I can give you access to maintain this package if you like, or anybody else who might be interested.

@wize-wiz I can commit to maintaining this library. I use it in several projects. Or you can grant rights to @NoahNxT if he is willing to support it. Developers really need this library.

**Comment by wize-wiz** [comment]
@NoahNxT @smskin I'll add you both as maintainers, just a sec.

**Comment by wize-wiz** [comment]
@NoahNxT @smskin Maybe it's best to open a new Issue to stay in contact if you need anything else.

You should have received an invite.

**Comment by NoahNxT** [comment]
@wize-wiz awesome!

**Comment by smskin** [comment]
@wize-wize I received and confirmed the invitation. Thank you for your trust!

**Comment by wize-wiz** [comment]
@smskin Yea just don't screw it up, haha kidding :D

**Pull request closed without merging**
