### PR TITLE
Allow an array to be used for dependencies

### PR DESCRIPTION
**Pull request by dtannen**
Allow ->dependsOn('field', ['value1', 'value2'])

### CODE REVIEW

**Comment by amaitu** [comment]
Is this likely to be merged soon? I'd like to use of this feature
thanks

**Comment by PKuebler** [comment]
@dtannen you rewrite all namespaces. its correct oder an error in this pull request?

**Comment by KillianH** [comment]
Any update @unxsist ?

**Comment by AleSpreafico** [comment]
Please merge it xD really need this one for a client! =D

**Comment by wize-wiz** [comment]
@dtannen why the namespace change? It's quite unusable to merge ..

**Pull request closed without merging**
