### PR TITLE
Add BelongsTo field compatibility

### PR DESCRIPTION
**Pull request by mikaelpopowicz**

### CODE REVIEW

**Comment by wize-wiz** [comment]
@mikaelpopowicz is this equivalent to #64 and issued here #39 #21 #29?

**Comment by mikaelpopowicz** [comment]
@wize-wiz it solves the issues you mentioned. It is not customizable like the #64

**Comment by wize-wiz** [comment]
Yea #64 uses a `setWatchable` which is passed through meta, which would solve compatability to other fields but that's something that could be added later.

Could you remove the lock file for node `.nvmrc` and add it to the git `.ignore`?

**Comment by wize-wiz** [comment]
@mikaelpopowicz great work. I'm going to build on this PR and drop #64, I think the `MorphTo` Field should work just like `BelongsTo`. Maybe I'm going to merge this PR first and then enhance to support `MorphTo` too.

**Pull request merged**
