### PR TITLE
New "dependsOnFalse" dependency option

### PR DESCRIPTION
**Pull request by mattivie14**
This new 'dependsOnFalse' function allows you to use 'not equal' logic, like: "if field is NOT equal to value"

### CODE REVIEW

**Comment by wize-wiz** [comment]
@mattivie14 the `dependsOn('field', false)` should now work just the same.

**Comment by wize-wiz** [comment]
Would it be better to call it `dependsOnNotEqualTo`? Calling it `dependsOnFalse` made me suggest it would depend on the value `false`.

**Comment by wize-wiz** [comment]
Now this made me come to an idea, how about a third parameter for the `dependsOn` method that would specify the operator, as in `=` by default, `!=`, `>`, etc ..

**Comment by ragingdave** [comment]
There is a new `dependsOnNot` method added now

**Pull request closed without merging**
